import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
const first='11111111-1111-4111-8111-111111111111',second='22222222-2222-4222-8222-222222222222',admin='33333333-3333-4333-8333-333333333333';
await db.exec(`CREATE ROLE anon;CREATE ROLE authenticated;CREATE SCHEMA auth;CREATE SCHEMA storage;
 CREATE TABLE auth.users(id UUID PRIMARY KEY,email TEXT);
 CREATE FUNCTION auth.uid() RETURNS UUID LANGUAGE SQL STABLE AS $$ SELECT NULLIF(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 CREATE TABLE storage.buckets(id TEXT PRIMARY KEY,name TEXT,public BOOLEAN,file_size_limit BIGINT,allowed_mime_types TEXT[]);
 CREATE TABLE storage.objects(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),bucket_id TEXT);
 ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;
 GRANT USAGE ON SCHEMA auth,storage,public TO anon,authenticated;GRANT EXECUTE ON FUNCTION auth.uid() TO anon,authenticated;`);
const schema=await readFile(new URL('../supabase_schema.sql',import.meta.url),'utf8');
await db.exec(schema);await db.exec('CREATE POLICY unsafe_orders ON public.orders FOR ALL USING(true) WITH CHECK(true);CREATE POLICY unsafe_wallets ON public.user_wallets FOR ALL USING(true) WITH CHECK(true);');await db.exec(schema);
await db.exec(`GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public,storage TO anon,authenticated;
 REVOKE ALL ON public.admin_users FROM anon,authenticated;
 INSERT INTO auth.users VALUES('${first}','first@example.com'),('${second}','second@example.com'),('${admin}','admin@example.com');
 INSERT INTO public.admin_users VALUES('${admin}');
 INSERT INTO public.products(id,name,category,price,weight,stock_quantity,unit_kg) VALUES('meat','Test meat','Test',200,'500g',20,0.5);
 INSERT INTO public.addresses(id,user_id,full_name,phone,house_flat,street_road,locality,city) VALUES('a1','${first}','First','911234567890','1','Road','Boko','Guwahati'),('a2','${second}','Second','911234567891','2','Road','Boko','Guwahati');`);
async function actor(id,role='authenticated'){await db.exec(`RESET ROLE;SET request.jwt.claim.sub='${id}';SET ROLE ${role};`);}
const fail=async(sql,params=[],pattern)=>assert.rejects(()=>db.query(sql,params),pattern);
let count=0;const check=async(name,fn)=>{await fn();count++;console.log('PASS '+name);};
const stock=async()=>Number((await db.query("SELECT stock_quantity FROM products WHERE id='meat'")).rows[0].stock_quantity);
const place=(request=crypto.randomUUID(),address='a1',items=[{productId:'meat',quantity:1}],payment='COD',coupon=null)=>db.query('SELECT (place_order($1,$2,$3,$4,$5)).*',[request,address,items===null?null:JSON.stringify(items),payment,coupon]);
await actor(first);await db.query('SELECT sync_my_profile($1,$2)',['First','911234567890']);
await check('migration applied twice',async()=>assert.equal((await db.query('SELECT * FROM profiles')).rows.length,1));
await check('customer cannot grant administrator access',()=>fail(`INSERT INTO admin_users VALUES('${first}')`,[],/permission denied|row-level/));
await check('customer sees only owned address and profile',async()=>{assert.equal((await db.query('SELECT * FROM addresses')).rows.length,1);assert.equal((await db.query('SELECT * FROM profiles')).rows.length,1);});
await check('customer cannot modify catalogue or forge balance',async()=>{await fail("INSERT INTO products(id,name,category,price) VALUES('bad','Bad','Bad',1)",[],/row-level/);await fail('INSERT INTO user_wallets(user_id,balance) VALUES($1,999999)',[first],/row-level/);});
await check('customer cannot approve deposits',()=>fail("SELECT review_wallet_deposit('x',true)",[],/Administrator/));
await check('checkout rejects another users address',()=>assert.rejects(()=>place(undefined,'a2'),/saved delivery address/));
await check('checkout rejects null or empty cart',async()=>{for(const items of [null,[]])await assert.rejects(()=>place(undefined,'a1',items),/Cart/);});
await check('checkout rejects malformed quantities',async()=>{for(const quantity of [0,-1,1.5,101,null])await assert.rejects(()=>place(undefined,'a1',[{productId:'meat',quantity}]),/quantity/);});
await check('checkout rejects fake gateway and null payment',async()=>{for(const payment of ['UPI',null])await assert.rejects(()=>place(undefined,'a1',undefined,payment),/gateway/);});
await check('changed quoted total is rejected without decrementing stock',async()=>{await fail('SELECT place_order($1,$2,$3,$4,$5,$6)',[crypto.randomUUID(),'a1',JSON.stringify([{productId:'meat',quantity:1}]),'COD',null,1],/Prices or fees/);assert.equal(await stock(),20);});
await check('outside delivery area is rejected',async()=>{await db.exec('RESET ROLE');await db.query("UPDATE addresses SET city='Other City' WHERE id='a1'");await actor(first);await assert.rejects(()=>place(),/Delivery is not available/);await db.exec('RESET ROLE');await db.query("UPDATE addresses SET city='Guwahati' WHERE id='a1'");await actor(first);});
const request=crypto.randomUUID();let order;
await check('server ignores client prices and recalculates totals',async()=>{order=(await place(request,'a1',[{productId:'meat',quantity:2,quantityKg:0.25,price:1}])).rows[0];assert.equal(Number(order.subtotal),200);assert.equal(Number(order.total_amount),250);assert.equal(order.payment_status,'Pending');});
await check('repeated request creates only one order and stock decrement',async()=>{assert.equal((await place(request)).rows[0].id,order.id);assert.equal((await db.query('SELECT * FROM orders')).rows.length,1);assert.equal(await stock(),19);});
await check('insufficient wallet payment rolls back all changes',async()=>{await assert.rejects(()=>place(undefined,'a1',undefined,'WALLET'),/Insufficient wallet/);assert.equal(await stock(),19);assert.equal((await db.query('SELECT * FROM orders')).rows.length,1);});
await db.query('SELECT request_wallet_deposit($1,$2)',[1000,'test-reference']);const deposit=(await db.query("SELECT * FROM wallet_transactions WHERE type='deposit'")).rows[0];
await actor(admin);
await check('deposit approval credits exactly once',async()=>{await db.query('SELECT review_wallet_deposit($1,true)',[deposit.id]);await fail('SELECT review_wallet_deposit($1,true)',[deposit.id],/pending deposits/);assert.equal(Number((await db.query('SELECT balance FROM user_wallets WHERE user_id=$1',[first])).rows[0].balance),1000);});
await db.query("INSERT INTO offers(id,details,is_active) VALUES('coupon',$1,true)",[JSON.stringify({couponCode:'TEST10',discountType:'percentage',discountValue:'10',validTill:'2099-12-31'})]);
await actor(first);let paid;
await check('wallet payment and coupon commit atomically',async()=>{paid=(await place(undefined,'a1',undefined,'WALLET','TEST10')).rows[0];assert.equal(Number(paid.discount),20);assert.equal(Number(paid.total_amount),229);assert.equal(paid.payment_status,'Paid');assert.equal(Number((await db.query('SELECT balance FROM user_wallets')).rows[0].balance),771);});
await check('invalid coupon rolls back inventory',async()=>{await assert.rejects(()=>place(undefined,'a1',undefined,'COD','BAD'),/coupon/);assert.equal(await stock(),18);});
await check('customer cannot mark order delivered',()=>fail('SELECT set_order_status($1,$2)',[paid.id,'Delivered'],/Administrator/));
await actor(second);
await check('another customer sees no orders or wallet balances',async()=>{assert.equal((await db.query('SELECT * FROM orders')).rows.length,0);assert.equal((await db.query('SELECT * FROM user_wallets')).rows.length,0);});
await actor(admin);
await check('cancellation refunds wallet and restores stock exactly once',async()=>{await db.query('SELECT set_order_status($1,$2)',[paid.id,'Cancelled']);await fail('SELECT set_order_status($1,$2)',[paid.id,'Cancelled'],/transition/);assert.equal(Number((await db.query('SELECT balance FROM user_wallets WHERE user_id=$1',[first])).rows[0].balance),1000);assert.equal(await stock(),19);});
await check('fulfillment cannot skip stages',()=>fail('SELECT set_order_status($1,$2)',[order.id,'Delivered'],/transition/));
for(const status of ['Preparing','On the Way','Delivered'])await db.query('SELECT set_order_status($1,$2)',[order.id,status]);
await actor(first);
await check('delivered order accepts one owned review',async()=>{await db.query('INSERT INTO reviews(order_id,user_id,rating) VALUES($1,$2,5)',[order.id,first]);await fail('INSERT INTO reviews(order_id,user_id,rating) VALUES($1,$2,5)',[order.id,first],/unique/);});
const ticket=(await db.query("INSERT INTO support_tickets(user_id,subject,status,messages) VALUES($1,'Help','Open','[]') RETURNING id",[first])).rows[0];await db.query('SELECT reply_to_ticket($1,$2)',[ticket.id,'Help me']);
await actor(second);
await check('other customer cannot reply to support ticket',()=>fail('SELECT reply_to_ticket($1,$2)',[ticket.id,'Unauthorized'],/not found/));
await actor(admin);await db.query('SELECT set_user_blocked($1,true)',[first]);await actor(first);
await check('blocked user cannot order',()=>assert.rejects(()=>place(),/blocked/));
await actor('','anon');
await check('anonymous visitor cannot read private orders or checkout',async()=>{assert.equal((await db.query('SELECT * FROM orders')).rows.length,0);await assert.rejects(()=>place(),/permission denied/);});
console.log(`\n${count} database checks passed. No external system accessed.`);await db.close();
