import React,{useState} from 'react';
import {supabase} from '../../lib/supabase';
import {useRows} from '../../lib/useData';
import {DataScreen,panelClass,buttonClass} from '../common/DataScreen';
export const HelpSupportScreen:React.FC<{onBack:()=>void;onNavigateTab:(tab:string)=>void}>=({onBack})=>{
 const {rows,loading,error,reload}=useRows('support_tickets',true);const [subject,setSubject]=useState('');const [message,setMessage]=useState('');const [reply,setReply]=useState<Record<string,string>>({});const [busy,setBusy]=useState(false);const [actionError,setActionError]=useState('');
 const create=async(e:React.FormEvent)=>{e.preventDefault();if(busy)return;setBusy(true);setActionError('');try{const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Please sign in');const {data:profile,error:pe}=await supabase.from('profiles').select('*').eq('id',user.id).single();if(pe)throw pe;const {data:ticket,error}=await supabase.from('support_tickets').insert({user_id:user.id,customer_name:profile.full_name,customer_phone:profile.phone,subject:subject.trim(),messages:[],status:'Open'}).select().single();if(error)throw error;const {error:replyError}=await supabase.rpc('reply_to_ticket',{p_id:ticket.id,p_text:message.trim()});if(replyError){setActionError('Ticket created. Send your message again below: '+replyError.message);}else{setSubject('');setMessage('');}await reload();}catch(error:any){setActionError(error.message);}finally{setBusy(false);}};
 const send=async(id:string)=>{if(busy || !reply[id]?.trim())return;setBusy(true);const {error}=await supabase.rpc('reply_to_ticket',{p_id:id,p_text:reply[id].trim()});if(error)setActionError(error.message);else{setReply(p=>({...p,[id]:''}));await reload();}setBusy(false);};
 return <DataScreen title="Help & Support" onBack={onBack} loading={loading} error={error || actionError}><form className={panelClass} onSubmit={create}><h2 className="font-bold">Contact Support</h2><label className="block">Subject<input required maxLength={200} value={subject} onChange={e=>setSubject(e.target.value)} className="border rounded-xl p-3 w-full"/></label><label className="block">Message<textarea required maxLength={4000} value={message} onChange={e=>setMessage(e.target.value)} className="border rounded-xl p-3 w-full"/></label><button disabled={busy} className={buttonClass}>Create Ticket</button></form><h2 className="font-bold">My Tickets</h2>{rows.map(t=><article key={t.id} className={panelClass}><h3 className="font-bold">{t.subject}</h3><p className="text-sm text-red-700">{t.status}</p>{(t.messages || []).map((m:any)=><p key={m.id} className="p-2 bg-slate-50 rounded-lg"><strong>{m.sender}: </strong>{m.text}</p>)}<input aria-label="Reply" maxLength={4000} value={reply[t.id] || ''} onChange={e=>setReply(p=>({...p,[t.id]:e.target.value}))} className="border rounded-xl p-3 w-full"/><button disabled={busy || !reply[t.id]?.trim()} className={buttonClass} onClick={()=>void send(t.id)}>Send Reply</button></article>)}{!loading && !rows.length && <p>No support tickets yet.</p>}</DataScreen>;
};
