import React,{useState} from 'react';
import {supabase} from '../../lib/supabase';
import {useRows} from '../../lib/useData';
import {DataScreen,panelClass,buttonClass} from '../common/DataScreen';
export interface WalletTransaction {id:string;amount:number;type:'deposit'|'payment'|'refund';status:'Pending'|'Approved'|'Rejected';utr?:string;date:string;notes?:string;}
export const WalletScreen:React.FC<{onBack:()=>void}>=({onBack})=>{
 const wallet=useRows('user_wallets',true);const tx=useRows('wallet_transactions',true);
 const [amount,setAmount]=useState('');const [reference,setReference]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 const upi=import.meta.env.VITE_MERCHANT_UPI_ID || '';
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try {const value=Number(amount);if(!Number.isFinite(value)||value<=0||value>50000)throw new Error('Enter an amount between ₹1 and ₹50,000');const {error}=await supabase.rpc('request_wallet_deposit',{p_amount:value,p_reference:reference.trim()});if(error)throw error;await tx.reload();setMessage('Deposit submitted for administrator verification. Balance changes only after approval.');setReference('');}catch(error:any){setError(error.message);}finally{setBusy(false);}};
 return <DataScreen title="Meat Ghar Wallet" onBack={onBack} loading={wallet.loading || tx.loading} error={error || wallet.error || tx.error}><article className={panelClass}><p>Available balance</p><strong className="text-3xl">₹{Number(wallet.rows[0]?.balance || 0).toFixed(2)}</strong></article>{upi ? <form onSubmit={submit} className={panelClass}><h2 className="font-bold">Add Funds</h2><p>Pay to <strong>{upi}</strong>, then submit your payment reference. Administrator approval is required.</p><label className="block">Amount (₹)<input required type="number" min="1" max="50000" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} className="border rounded-xl p-3 w-full"/></label><a className="text-red-700 font-bold block" href={`upi://pay?pa=${encodeURIComponent(upi)}&pn=Meat%20Ghar&am=${encodeURIComponent(amount)}&cu=INR`}>Open UPI app</a><label className="block">Payment reference<input required minLength={6} value={reference} onChange={e=>setReference(e.target.value)} className="border rounded-xl p-3 w-full"/></label><button disabled={busy} className={buttonClass}>Submit Deposit</button>{message && <p role="status">{message}</p>}</form> : <p className="text-sm">Wallet top-ups are unavailable until the store configures its payment account.</p>}<h2 className="font-bold">Transactions</h2>{tx.rows.map(t=><article key={t.id} className={panelClass}><p className="flex justify-between"><strong>{t.type}</strong><strong>₹{Number(t.amount).toFixed(2)}</strong></p><p>{t.status} · {new Date(t.created_at).toLocaleString()}</p><p>{t.notes}</p></article>)}{!tx.loading && !tx.rows.length && <p>No transactions yet.</p>}</DataScreen>;
};
