import React,{useState} from 'react';
import {useAdmin} from '../AdminContext';
import {AdminHeader} from '../components/AdminHeader';
import {panelClass,buttonClass} from '../../common/DataScreen';
export const FlashDealsScreen:React.FC=()=>{
 const {flashDeals,products,addFlashDeal,deleteFlashDeal,toggleFlashDealActive}=useAdmin();const [productId,setProductId]=useState('');const [title,setTitle]=useState('');const [minutes,setMinutes]=useState('120');
 const save=(e:React.FormEvent)=>{e.preventDefault();const p=products.find(p=>p.id===productId);if(!p)return;addFlashDeal({title,productId:p.id,productName:p.name,category:p.category,categoryId:p.categoryId,price:p.price,originalPrice:p.originalPrice || p.price,discountPercentage:p.originalPrice && p.originalPrice>p.price?Math.round((1-p.price/p.originalPrice)*100)+'% OFF':'Featured',image:p.image,stockLeft:p.stockQuantity,totalStock:p.stockQuantity,endsInMinutes:Number(minutes),unit:p.unit,isActive:true});};
 return <div className="h-full flex flex-col bg-slate-50"><AdminHeader title="Flash Deals" showBack/><main className="flex-1 min-h-0 overflow-y-auto p-4 space-y-4"><form onSubmit={save} className={panelClass}><h2 className="font-bold">Feature a Product</h2><label className="block">Title<input required value={title} onChange={e=>setTitle(e.target.value)} className="border rounded-xl p-3 w-full"/></label><label className="block">Product<select required value={productId} onChange={e=>setProductId(e.target.value)} className="border rounded-xl p-3 w-full"><option value="">Select a catalogue product</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} · ₹{p.price}</option>)}</select></label><label className="block">Duration (minutes)<input required type="number" min="1" max="10080" value={minutes} onChange={e=>setMinutes(e.target.value)} className="border rounded-xl p-3 w-full"/></label><p className="text-xs text-slate-500">The current catalogue price and stock are used. Set a product's selling price in Products before featuring it.</p><button className={buttonClass} disabled={!productId}>Create Deal</button></form>{flashDeals.map(d=><article key={d.id} className={panelClass}><h2 className="font-bold">{d.title}</h2><p>{d.productName}</p><p className="text-xs">{d.endsAt ? 'Ends '+new Date(d.endsAt).toLocaleString():'No expiry set'}</p><div className="flex gap-3"><button className={buttonClass} onClick={()=>toggleFlashDealActive(d.id)}>{d.isActive?'Deactivate':'Activate'}</button><button className="text-red-700 font-bold" onClick={()=>{if(confirm('Delete this deal?'))deleteFlashDeal(d.id);}}>Delete</button></div></article>)}</main></div>;
};
