import React,{useState} from 'react';
import {useAdmin} from '../AdminContext';
import {AdminHeader} from '../components/AdminHeader';
import {useRows} from '../../../lib/useData';
import {supabase} from '../../../lib/supabase';
import {panelClass,buttonClass} from '../../common/DataScreen';
export const ReportsSettingsScreen:React.FC=()=>{
 const {orders,users,products,walletRequests,approveWalletRequest,rejectWalletRequest,showToast}=useAdmin();const settings=useRows('store_settings');const [segment,setSegment]=useState('reports');const [busy,setBusy]=useState(false);
 const exportData=(name:string,rows:Record<string,unknown>[])=>{if(!rows.length){showToast('No records to export');return;}const cols=Object.keys(rows[0]);const quote=(v:unknown)=>{const s=typeof v==='object'?JSON.stringify(v):String(v ?? '');return '"'+(/^[=+@\-\t\r]/.test(s)?"'"+s:s).replaceAll('"','""')+'"';};const csv=[cols.map(quote).join(','),...rows.map(r=>cols.map(c=>quote(r[c])).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`meat-ghar-${name}.csv`;a.click();URL.revokeObjectURL(url);showToast('CSV downloaded');};
 const save=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(busy)return;const fields=new FormData(e.currentTarget);setBusy(true);const row={delivery_fee:Number(fields.get('delivery_fee')),free_delivery_threshold:Number(fields.get('free_delivery_threshold')),tax_percent:Number(fields.get('tax_percent')),is_open:fields.get('is_open')==='on',service_city:String(fields.get('service_city') || '').trim(),service_areas:String(fields.get('service_areas') || '').split(',').map(s=>s.trim()).filter(Boolean)};if(!row.service_city || !row.service_areas.length || Object.values(row).some(v=>typeof v==='number' && (!Number.isFinite(v)||v<0)) || row.tax_percent>100){showToast('Invalid pricing settings');setBusy(false);return;}const {error}=await supabase.from('store_settings').update(row).eq('id',true).select().single();if(error)showToast(error.message);else{await settings.reload();showToast('Settings saved');}setBusy(false);};
 return <div className="h-full flex flex-col bg-slate-50"><AdminHeader title="Reports & Settings" showBack/><main className="flex-1 min-h-0 overflow-y-auto p-4 space-y-4"><div className="flex bg-white rounded-xl border p-1">{['reports','settings','wallet'].map(s=><button key={s} className={'flex-1 p-3 text-sm font-bold rounded-xl '+(segment===s?'bg-red-700 text-white':'')} onClick={()=>setSegment(s)}>{s==='wallet'?'Wallet Requests':s.charAt(0).toUpperCase()+s.slice(1)}</button>)}</div>{segment==='reports' && <article className={panelClass}><p>Orders: {orders.length}</p><p>Users: {users.length}</p><p>Products: {products.length}</p><p>Delivered revenue: ₹{orders.filter(o=>o.status==='Delivered').reduce((n,o)=>n+o.total,0).toFixed(2)}</p>{[['orders',orders],['users',users],['products',products]].map(([name,rows])=><button key={name as string} className={buttonClass+' mr-2'} onClick={()=>exportData(name as string,rows as unknown as Record<string,unknown>[])}>Export {name as string} CSV</button>)}</article>}{segment==='settings' && <>{settings.error && <p role="alert">{settings.error}</p>}{settings.rows[0] && <form key={JSON.stringify(settings.rows[0])} className={panelClass} onSubmit={save}><label className="block"><input name="is_open" type="checkbox" defaultChecked={settings.rows[0].is_open}/> Store open</label>{[['delivery_fee','Delivery fee (₹)'],['free_delivery_threshold','Free delivery threshold (₹)'],['tax_percent','Tax (%)']].map(([name,label])=><label key={name} className="block">{label}<input name={name} required type="number" min="0" max={name==='tax_percent'?100:undefined} step="0.01" defaultValue={settings.rows[0][name]} className="border p-3 rounded-xl w-full"/></label>)}<label className="block">Service city<input name="service_city" required defaultValue={settings.rows[0].service_city} className="border p-3 rounded-xl w-full"/></label><label className="block">Delivery areas (comma separated)<input name="service_areas" required defaultValue={(settings.rows[0].service_areas || []).join(', ')} className="border p-3 rounded-xl w-full"/></label><button disabled={busy} className={buttonClass}>Save Settings</button><p className="text-xs text-slate-500">Payment accounts and device push secrets are configured securely during deployment.</p></form>}</>}{segment==='wallet' && <>{walletRequests.filter(r=>r.type==='deposit').map(r=><article key={r.id} className={panelClass}><p className="break-all">User: {r.user_id}</p><p>₹{r.amount} · {r.status}</p><p>Reference: {r.qr_reference}</p>{r.status==='Pending' && <div className="flex gap-3"><button className={buttonClass} onClick={()=>{if(confirm('Have you independently verified receipt of this payment?'))void approveWalletRequest(r.id);}}>Approve</button><button className="text-red-700 font-bold" onClick={()=>void rejectWalletRequest(r.id)}>Reject</button></div>}</article>)}{!walletRequests.some(r=>r.type==='deposit') && <p>No deposit requests.</p>}</>}</main></div>;
};
